"""Phase 1 acceptance (SPEC §14): import §5.2, export it identically, diff two imports."""

from app.services.dsl import apply_document, export_dsl, load_dsl
from app.services.dsl.registry import Lifecycle


def _import(text: str, graph=None):
    return apply_document(graph, load_dsl(text))


def test_example_imports_cleanly(example_dsl):
    result = _import(example_dsl)
    assert result.validation.ok, result.validation.errors
    g = result.graph
    assert set(g.elements) == {"portal-web", "api-pagos", "originacion"}
    assert set(g.relations) == {"r-portal-usa-pagos", "r-orig-usa-pagos"}
    assert set(g.views) == {"vista-app-pagos", "proceso-originacion"}


def test_alias_normalized_to_canonical(example_dsl):
    g = _import(example_dsl).graph
    # DSL wrote `kind: uses`; stored canonically as `serving`.
    assert g.relations["r-portal-usa-pagos"].kind == "serving"


def test_roundtrip_is_semantically_identical(example_dsl):
    """export(import(x)) == x  (the Phase 1 acceptance criterion)."""
    g1 = _import(example_dsl).graph
    g2 = _import(export_dsl(g1)).graph
    assert g1.model_dump() == g2.model_dump()


def test_autogenerated_relation_id_is_stable(example_dsl, patch_dsl):
    """A patch relation with no id gets a deterministic slug id."""
    base = _import(example_dsl).graph
    g = apply_document(base, load_dsl(patch_dsl)).graph
    assert "r-originacion-serving-motor-scoring" in g.relations


def test_patch_applies_all_operations(example_dsl, patch_dsl):
    base = _import(example_dsl).graph
    result = apply_document(base, load_dsl(patch_dsl))
    g = result.graph
    assert "motor-scoring" in g.elements                       # add_elements
    assert g.elements["api-pagos"].lifecycle == Lifecycle.deprecated  # update_elements
    assert "r-portal-usa-pagos" not in g.relations             # remove_relations
    assert result.validation.ok, result.validation.errors


def test_diff_between_two_imports(example_dsl, patch_dsl):
    base = _import(example_dsl).graph
    result = apply_document(base, load_dsl(patch_dsl))
    d = result.diff
    assert "motor-scoring" in d.elements.added
    assert "r-portal-usa-pagos" in d.relations.removed
    modified = {m.id for m in d.elements.modified}
    assert "api-pagos" in modified
    lifecycle_change = next(
        c for m in d.elements.modified if m.id == "api-pagos" for c in m.changes if c.field == "lifecycle"
    )
    assert lifecycle_change.before == "active"
    assert lifecycle_change.after == "deprecated"
